name: CI/CD Pipeline for ai

on:
  push:
    branches:
      - main  # Jalankan pipeline setiap ada perubahan di branch 'main'
  workflow_dispatch:  # Memungkinkan untuk menjalankan secara manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode dari repo GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Login ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -f ai/deployment/Dockerfile --tag predict-chicken-test .
        docker tag predict-chicken-test:latest royrobin99/predict-chicken-test:latest

    # 4. Push Docker Image ke Docker Hub
    - name: Push Docker Image
      run: |
        docker push royrobin99/predict-chicken-test:latest

    # 5. Login ke IBM Cloud
    - name: IBM Cloud Login
      run: |
        ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }}
        ibmcloud target --region us-south

    # 6. Deploy ke IBM Cloud Code Engine
    - name: Deploy to IBM Cloud Code Engine
      run: |
        ibmcloud ce application apply \
          --name predict-chicken-test \
          --image royrobin99/predict-chicken-test:latest \
          --cpu 2 --memory 4Gi \
          --ephemeral-storage 1Gi \
          --min-scale 0 --max-scale 1 \
          --port 5000
