name: CI/CD Pipeline for ai

on:
  workflow_dispatch:  # Hanya berjalan jika dipicu secara manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        # Menyebutkan path yang benar ke folder Deployment
        docker build --tag predict-chicken-test ./ai/Deployment
        docker tag predict-chicken-test:latest royrobin99/predict-chicken-test:latest

    - name: Push Docker Image
      run: |
        docker push royrobin99/predict-chicken-test:latest

    - name: IBM Cloud Login
      run: |
        ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }}
        ibmcloud target --region us-south

    - name: Deploy to IBM Cloud Code Engine
      run: |
        ibmcloud ce application apply \
          --name predict-chicken-test \
          --image royrobin99/predict-chicken-test:latest \
          --cpu 2 --memory 4Gi \
          --ephemeral-storage 1Gi \
          --min-scale 0 --max-scale 1 \
          --port 5000
